### ISSUE TITLE
Ulib breaks it?

### ISSUE THREAD

**Issue by bubblegam** [MattJeanes/Joystick-Module#10]
[ULib] addons/joystick/lua/autorun/client/joyconfig.lua:1532: attempt to index global 'joynet' (a nil value)
  1. menuclosed - addons/joystick/lua/autorun/client/joyconfig.lua:1532
   2. fn - addons/joystick/lua/autorun/client/joyconfig.lua:1537
    3. unknown - lua/ulib/shared/hook.lua:109

**Comment by MattJeanes** [comment]
ULib overrides the hook system for some weird reason but is likely not the cause of your issue here. When do you get this error message?

**Comment by bubblegam** [comment]
i fixed the issue, just had to reinstall all my addons, but it was when i closed the window for the controller setup

**Comment by MattJeanes** [comment]
Ah cool

**Comment by bubblegam** [comment]
ill let you know of any other errors i get with it
