### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by SilverMight** [MattJeanes/Joystick-Module#11]
Forgive me if I'm doing something wrong here.
I've installed the module in garrysmod/lua/bin and the addon correctly, however when I type in joyconfig in console it just throws command not found back at me. Does this addon not work on Linux?
The addon is properly installed on the server and players are using it fine, too.

**Comment by MattJeanes** [comment]
Hi Silver, unfortunately this module is not supported on Linux as the C++ calls use DInput which is a Windows feature.

The C++ binary module is only needed clientside, but the joystick addon it comes with is required on the client and server, and the server can be running Linux as it doesn't need the binary module.

Hope that helps!

**Comment by SilverMight** [comment]
Ah, that sucks. Thanks for the clarification.
