### ISSUE TITLE
Couldn't include file 'includes\modules\joystick.lua (File not found)

### ISSUE THREAD

**Issue by Havocking1992** [MattJeanes/Joystick-Module#12]
Hello, 
i've done installation as what is said in instructions, but it still gives me those errors:

`Couldn't include file 'includes\modules\joystick.lua (File not found)`
`(@addons/joystick/lua/autorun/client/joystick.lua (line 63))`

`[ERROR] addons/joystick/lua/autorun/client/joystick.lua:63: Module not found!`
`  1. require - [C]:-1`
`   2. unknown - addons/joystick/lua/autorun/client/joystick.lua:63`

**Comment by MattJeanes** [comment]
Hi there please see my comments and follow the thread on this issue as it appears to be the same problem

https://github.com/MattJeanes/Joystick-Module/issues/13
