### ISSUE TITLE
Unknown command: joyconfig

### ISSUE THREAD

**Issue by Papyrus61** [MattJeanes/Joystick-Module#15]
every time I try to load up the tool it will say that and not even bring up the settings menu.

**Comment by Titanic4** [comment]
Have you tried using 32-bit version of Garry's Mod? The required module wasn't compiled for 64-bit version yet.

**Comment by MattJeanes** [comment]
Hi there, yes as Titanic4 said the module does not work under 64 bit gmod and only works on windows at the moment, see this issue for more info

https://github.com/MattJeanes/Joystick-Module/issues/13
