### ISSUE TITLE
steering wheel causes player's camera to turn fast with it

### ISSUE THREAD

**Issue by samdisk11** [MattJeanes/Joystick-Module#41]
hello, i run a server with this module installed, and a player is facing a issue with his steering wheel where if he turns the steering wheel all the way it moves the camera. is there a way to disable/reconfigure this?

the server in question is steam://connect/209.126.12.232:27018 incase its a problem with the gamemode/plugins i have or his steering wheel.

**Comment by MattJeanes** [comment]
I don't see how the addon could be the cause of this, it's more likely that the wheel is bound to some control within the game and turning it all the way to the right or left it activates that command. I'd recommend getting your player to check his controls in the game and see if it's bound anywhere.

**Comment by samdisk11** [comment]
ok i asked him and he has fixed the problem

**Comment by MattJeanes** [comment]
Good to hear
