### ISSUE TITLE
Getting corrupted data

### ISSUE THREAD

**Issue by thegrb93** [MattJeanes/Joystick-Module#7]
For some reason many buttons are being detected as POVs and their values are powers of 2 when pressed. I think something fucky is going on with direct input.

**Comment by thegrb93** [comment]
Maybe the binary needs to be recompiled? I'm not sure how to do that unfortunately.

**Comment by MattJeanes** [comment]
Hey there, unfortunately I didn't write the binary module for this, that was NightEagle. He sort of disappeared so to make sure the module remained available I'm hosting it here and fixing the lua side of things if it breaks. You may have better luck asking in the Facepunch thread in the readme. Sorry.

**Comment by thegrb93** [comment]
I never followed up on this, but recompiling the module fixed it.

**Comment by MattJeanes** [comment]
Hey do you have the updated binary module? Probably makes sense for me to include it in here if it still works!

**Comment by thegrb93** [comment]
https://github.com/thegrb93/StarfallEx/raw/master/gmcl_joystick_win32.dll
https://github.com/thegrb93/StarfallEx/raw/master/gmcl_joystick_win64.dll

**Comment by MattJeanes** [comment]
Very nice, thank you! I will include these in this repository
