### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by Mysterypancake1** [MattJeanes/Joystick-Module#8]
I know this module is ancient and this question is probably absolutely stupid, but can't you already access joystick input using [IsButtonDown](https://wiki.garrysmod.com/page/input/IsButtonDown) and [Joystick enums](https://wiki.garrysmod.com/page/Enums/JOYSTICK)?

[I made a tiny Lua module for binding buttons a while ago](https://github.com/Mysterypancake1/GMod-Binding), and it seems you can detect joystick input using it, since it uses IsButtonDown. I haven't tried your module yet, but I just wanted to know if you can get more joystick functionality from using a DLL.

**Comment by MattJeanes** [comment]
Fitting avatar!

I'm not 100% sure, I didn't make this module - that was NightEagle, only maintaining the Lua part of it now and hosting it here as all the original links went down years ago.

However, reading the FP thread this module seems to be a DirectInput interface, and my understanding is that if you can bind the joystick keys, it's only some of them and it doesn't look like you can bind specific axis' or get a percentage of how much the axis has changed for gradual controller-like input, whereas this module allows you to do all of that.

**Comment by Mysterypancake1** [comment]
Okay, thanks for the explanation! You can close this now I guess

**Comment by MattJeanes** [comment]
Cool, no worries
