### ISSUE TITLE
Where do I put the SRC folder?

### ISSUE THREAD

**Issue by Puffycheeses** [MattJeanes/Joystick-Module#9]
I feel like have put it in the wrong place as I am getting

`Joystick module is not loaded!`

error when I type joyconfig or choose it in wire.

I have just put it into /common/GarrysMod/garrysmod

**Comment by MattJeanes** [comment]
Please follow the instructions in the readme, src folder goes nowhere it is the modules source code

**Comment by dvdvideo1234** [comment]
Fixed with PR https://github.com/MattJeanes/Joystick-Module/pull/17

Users do not need to install it manually under windows. They have to clone the repo and run the `install.bat`

**Comment by MattJeanes** [comment]
Closing due to above PR and also I commented about where it should go
